"""Ed25519 identity for the AgentBnB Hermes plugin.

Generates and persists an Ed25519 keypair, derives the ``did:key`` and
``did:agentbnb`` identifiers, and signs request payloads for HTTP / WebSocket
auth against the AgentBnB Hub.

The on-disk format mirrors the agreement used elsewhere in AgentBnB:

    ~/.hermes/agentbnb/key.json
    {
      "version": 1,
      "did_key": "did:key:z6Mk...",
      "did_agentbnb": "did:agentbnb:6df74745403944c4",
      "agent_id": "6df74745403944c4",
      "public_key_hex": "<64 hex chars>",
      "private_key_hex": "<64 hex chars>",     # 32 bytes seed (NaCl signing key)
      "created_at": "2026-05-04T01:00:00Z"
    }

The file is written with ``0o600`` permissions. The private key never leaves
this file — sign operations live in this module.

Multibase / multicodec encoding mirrors ``src/identity/did.ts`` so DIDs
generated by the Python plugin and the TypeScript core resolve identically.
"""

from __future__ import annotations

import hashlib
import json
import os
import stat
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from nacl.encoding import HexEncoder
from nacl.signing import SigningKey, VerifyKey

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Ed25519 multicodec prefix per https://github.com/multiformats/multicodec
_ED25519_MULTICODEC_PREFIX = b"\xed\x01"

# RFC 4648 base58btc alphabet (Bitcoin)
_BASE58BTC_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

# Identity file format version — bump if schema changes
_KEY_FILE_VERSION = 1
_KEY_FILENAME = "key.json"


class IdentityError(Exception):
    """Raised when identity setup or loading fails."""


# ---------------------------------------------------------------------------
# Multibase / multicodec
# ---------------------------------------------------------------------------

def _base58btc_encode(data: bytes) -> str:
    """Encode bytes as base58btc (Bitcoin alphabet) with leading-zero handling."""
    if not data:
        return ""

    n = int.from_bytes(data, "big")
    out: list[str] = []
    while n > 0:
        n, rem = divmod(n, 58)
        out.append(_BASE58BTC_ALPHABET[rem])

    # Preserve leading 0x00 bytes as leading '1' characters (base58btc spec)
    leading_zeros = 0
    for byte in data:
        if byte == 0:
            leading_zeros += 1
        else:
            break

    return ("1" * leading_zeros) + "".join(reversed(out))


def _to_multibase_key(raw_pubkey: bytes) -> str:
    """Wrap a 32-byte Ed25519 pubkey as multibase ``z<base58btc(0xed01||pubkey)>``."""
    if len(raw_pubkey) != 32:
        raise IdentityError(
            f"Expected 32-byte Ed25519 public key, got {len(raw_pubkey)} bytes"
        )
    multicodec = _ED25519_MULTICODEC_PREFIX + raw_pubkey
    return "z" + _base58btc_encode(multicodec)


def to_did_key(pubkey_hex: str) -> str:
    """Derive a ``did:key`` DID from a hex-encoded Ed25519 public key.

    Mirrors ``toDIDKey`` in ``src/identity/did.ts`` so DIDs are byte-equal
    across the TypeScript core and Python plugin.
    """
    raw = bytes.fromhex(pubkey_hex)
    return f"did:key:{_to_multibase_key(raw)}"


def to_did_agentbnb(agent_id: str) -> str:
    """Build a ``did:agentbnb:<agent_id>`` DID from a 16-char hex agent id."""
    if not agent_id or len(agent_id) != 16 or not all(c in "0123456789abcdef" for c in agent_id):
        raise IdentityError(
            f"Invalid agent_id: must be 16 lowercase hex chars, got {agent_id!r}"
        )
    return f"did:agentbnb:{agent_id}"


def derive_agent_id(pubkey_hex: str) -> str:
    """Derive a stable 16-hex-char agent id from a public key.

    Uses SHA-256 truncated to 8 bytes (16 hex chars). This mirrors the
    derivation used by the TS core for cross-language consistency. If the TS
    core's derivation logic changes, update both sides together.
    """
    raw = bytes.fromhex(pubkey_hex)
    digest = hashlib.sha256(raw).digest()
    return digest[:8].hex()


# ---------------------------------------------------------------------------
# Identity dataclass
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AgentBnbIdentity:
    """A loaded AgentBnB identity for the Hermes plugin.

    Holds the public/private key pair plus pre-computed DIDs. The private key
    never leaves this object's lexical scope inside the plugin process; only
    ``sign(...)`` exposes any cryptographic capability.
    """

    did_key: str
    did_agentbnb: str
    agent_id: str
    public_key_hex: str
    _signing_key: SigningKey
    created_at: str

    def sign(self, message: bytes) -> bytes:
        """Sign a message with this identity's Ed25519 private key.

        Returns the raw 64-byte signature (NOT base64). Caller is responsible
        for any encoding required by the downstream protocol.
        """
        return bytes(self._signing_key.sign(message).signature)

    def verify_key(self) -> VerifyKey:
        """Expose the public verification key for round-tripping in tests."""
        return self._signing_key.verify_key

    # Repr without leaking private material
    def __repr__(self) -> str:  # pragma: no cover — cosmetic only
        return (
            f"AgentBnbIdentity(did_key={self.did_key!r}, agent_id={self.agent_id!r}, "
            "private_key=<redacted>)"
        )


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def _key_file_path(identity_dir: str | Path) -> Path:
    """Resolve the on-disk path for the identity key file."""
    return Path(identity_dir).expanduser() / _KEY_FILENAME


def _write_key_file(path: Path, payload: dict[str, str | int]) -> None:
    """Write the key file with restrictive permissions (0o600)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    # Tighten permissions — best effort on platforms that support POSIX modes
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass  # Windows / sandboxed FS — tolerate but log via callers


def _read_key_file(path: Path) -> dict[str, str | int]:
    """Read and validate the key file structure."""
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise IdentityError(f"Could not read identity file at {path}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise IdentityError(f"Identity file at {path} is not valid JSON: {exc}") from exc
    if data.get("version") != _KEY_FILE_VERSION:
        raise IdentityError(
            f"Identity file version mismatch — got {data.get('version')!r}, expected "
            f"{_KEY_FILE_VERSION}. Delete the file and re-run `hermes agentbnb publish` "
            "to regenerate."
        )
    return data


def _build_identity_payload(signing_key: SigningKey) -> dict[str, str | int]:
    """Build the JSON-serialisable payload for a fresh identity."""
    pub_hex = signing_key.verify_key.encode(encoder=HexEncoder).decode("ascii")
    priv_hex = signing_key.encode(encoder=HexEncoder).decode("ascii")
    agent_id = derive_agent_id(pub_hex)
    return {
        "version": _KEY_FILE_VERSION,
        "did_key": to_did_key(pub_hex),
        "did_agentbnb": to_did_agentbnb(agent_id),
        "agent_id": agent_id,
        "public_key_hex": pub_hex,
        "private_key_hex": priv_hex,
        "created_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def _identity_from_payload(payload: dict[str, str | int]) -> AgentBnbIdentity:
    """Reconstruct an ``AgentBnbIdentity`` from a parsed key file payload."""
    priv_hex = payload["private_key_hex"]
    signing_key = SigningKey(bytes.fromhex(str(priv_hex)))
    return AgentBnbIdentity(
        did_key=str(payload["did_key"]),
        did_agentbnb=str(payload["did_agentbnb"]),
        agent_id=str(payload["agent_id"]),
        public_key_hex=str(payload["public_key_hex"]),
        _signing_key=signing_key,
        created_at=str(payload["created_at"]),
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def ensure_identity(identity_dir: str | Path = "~/.hermes/agentbnb") -> AgentBnbIdentity:
    """Load the AgentBnB identity, generating it on first run.

    On first run:
    - creates ``identity_dir`` if absent
    - generates a fresh Ed25519 keypair
    - derives ``did:key`` and ``did:agentbnb``
    - writes ``key.json`` with ``0o600`` permissions
    - returns the loaded identity

    On subsequent runs: simply loads and validates the existing file.

    Args:
        identity_dir: Directory holding ``key.json``. Defaults to
            ``~/.hermes/agentbnb`` to align with Hermes plugin conventions.

    Returns:
        A loaded ``AgentBnbIdentity``.

    Raises:
        IdentityError: When the file exists but is corrupted, has wrong
            schema version, or the directory is not writable.
    """
    path = _key_file_path(identity_dir)

    if path.exists():
        return _identity_from_payload(_read_key_file(path))

    signing_key = SigningKey.generate()
    payload = _build_identity_payload(signing_key)
    _write_key_file(path, payload)
    return _identity_from_payload(payload)


def load_identity(identity_dir: str | Path = "~/.hermes/agentbnb") -> AgentBnbIdentity:
    """Load an existing identity. Raises if absent.

    Use ``ensure_identity`` for first-run generation; ``load_identity`` is the
    safer choice in code paths (e.g. ``hermes agentbnb status``) that should
    fail loudly if the user has not yet published.
    """
    path = _key_file_path(identity_dir)
    if not path.exists():
        raise IdentityError(
            f"No AgentBnB identity at {path}. Run `hermes agentbnb publish` first."
        )
    return _identity_from_payload(_read_key_file(path))
